export const SEO = {
  author: 'Nicolas Duran Garces',
  jobTitle: 'Ingeniero de software backend',
  siteName: 'Nicolas Duran Garces · Software Engineer',
  tagline: 'Ingeniero de software que lidera plataformas backend escalables, APIs observables y despliegues con Docker y Nginx.',
  siteUrl: 'https://nicolasdurangarces.com',
  description:
    'Nicolas Duran Garces (NIDUGA) - Ingeniero de software especializado en backend Python (FastAPI, Django) y arquitectura de APIs escalables. Ayudo a equipos a construir plataformas backend medibles en Python, FastAPI y Node, además de frontends en React cuando un feature necesita visión end-to-end. Opero con métricas, automatización CI/CD y mentalidad de producto.',
  locale: 'es_CO',
  alternateLocale: 'en_US',
  keywords: [
    'Nicolas Duran Garces',
    'NIDUGA',
    'niduga',
    'Nicolas Duran',
    'Duran Garces',
    'Ingeniero de software',
    'Software engineer Colombia',
    'Backend developer',
    'Backend Python',
    'FastAPI developer',
    'FastAPI',
    'Python backend specialist',
    'Desarrollador React',
    'Full stack developer',
    'DevOps engineer',
    'DevOps',
    'Arquitectura limpia',
    'Clean architecture',
    'Docker',
    'Nginx',
    'Node.js backend',
    'TypeScript developer',
    'API development',
    'Microservices',
    'Serverless architecture',
    'AWS Lambda',
    'Backend engineer Armenia Colombia',
    'Software engineer Quindio',
  ],
  twitter: undefined,
  image: '/og-image.png',
  sameAs: [
    'https://github.com/NicolasDuranGarces',
    'https://www.linkedin.com/in/garcesnicolas/',
    'mailto:niduga@outlook.es',
  ],
  contact: {
    email: 'niduga@outlook.es',
    location: 'Bogotá, Colombia',
    availability: 'Disponible para roles backend senior, arquitectura y consultoría DevOps.',
  },
  worksFor: {
    name: 'Freelance / Consultor independiente',
  },
}
